os:
  - linux
services: 
  - docker
language: node_js
node_js:
  - "9.5.0"
jdk:
  - oraclejdk8
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
sudo: false
cache:
  directories:
    - client/node_modules
    - $HOME/.m2/repository
env:
  global:
    - NODE_VERSION=9.5.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - PATH=./client/node_modules/.bin:$PATH
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jdk_switcher use oraclejdk8
  - java -version
install:
  - cd client && rm package-lock.json && npm install
script:
  - ng test --watch=false && npm build
  - cd ../server && ./mvnw -q clean test && ./mvnw -q clean package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
