os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "9.5.0"
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.yarn-cache
env:
  global:
    - NODE_VERSION=9.5.0
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
install:
  - npm install -g @angular/cli
  - npm install
script:
  - cd server && ./mvnw -q clean test
  - cd ../client && yarn test
  - cd ../server && ./mvnw -q package -Pprod -DskipTests
  - cd ../client && yarn build
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
